### PR TITLE
Migrate `ArrayHolder` test

### PR DESCRIPTION
**Pull request by JakeWharton**
The `hashCode` logic for primitive arrays was broken in that it would return the data class function to compute the `hashCode`. This should have been the instance-based function, which should have failed the JVM tests. Somehow, this only failed in JS and not JVM or native. Updated to the logic to use the correct `contentHashCode` function instead.

Generated JS diff:
```diff
 protoOf(ArrayHolder).hashCode = function () {
   var result = contentDeepHashCode(this.stringArray_1);
   result = imul(result, 31) + (this.nullableStringArray_1 == null ? 0 : contentDeepHashCode(this.nullableStringArray_1)) | 0;
-  result = imul(result, 31) + hashCode(this.booleanArray_1) | 0;
+  result = imul(result, 31) + contentHashCode(this.booleanArray_1) | 0;
-  result = imul(result, 31) + (this.nullableBooleanArray_1 == null ? 0 : hashCode(this.nullableBooleanArray_1)) | 0;
+  result = imul(result, 31) + (this.nullableBooleanArray_1 == null ? 0 : contentHashCode(this.nullableBooleanArray_1)) | 0;
-  result = imul(result, 31) + hashCode(this.byteArray_1) | 0;
+  result = imul(result, 31) + contentHashCode_0(this.byteArray_1) | 0;
-  result = imul(result, 31) + (this.nullableByteArray_1 == null ? 0 : hashCode(this.nullableByteArray_1)) | 0;
+  result = imul(result, 31) + (this.nullableByteArray_1 == null ? 0 : contentHashCode_0(this.nullableByteArray_1)) | 0;
-  result = imul(result, 31) + hashCode(this.charArray_1) | 0;
+  result = imul(result, 31) + contentHashCode_1(this.charArray_1) | 0;
-  result = imul(result, 31) + (this.nullableCharArray_1 == null ? 0 : hashCode(this.nullableCharArray_1)) | 0;
+  result = imul(result, 31) + (this.nullableCharArray_1 == null ? 0 : contentHashCode_1(this.nullableCharArray_1)) | 0;
-  result = imul(result, 31) + hashCode(this.shortArray_1) | 0;
+  result = imul(result, 31) + contentHashCode_2(this.shortArray_1) | 0;
-  result = imul(result, 31) + (this.nullableShortArray_1 == null ? 0 : hashCode(this.nullableShortArray_1)) | 0;
+  result = imul(result, 31) + (this.nullableShortArray_1 == null ? 0 : contentHashCode_2(this.nullableShortArray_1)) | 0;
-  result = imul(result, 31) + hashCode(this.intArray_1) | 0;
+  result = imul(result, 31) + contentHashCode_3(this.intArray_1) | 0;
-  result = imul(result, 31) + (this.nullableIntArray_1 == null ? 0 : hashCode(this.nullableIntArray_1)) | 0;
+  result = imul(result, 31) + (this.nullableIntArray_1 == null ? 0 : contentHashCode_3(this.nullableIntArray_1)) | 0;
-  result = imul(result, 31) + hashCode(this.longArray_1) | 0;
+  result = imul(result, 31) + contentHashCode_4(this.longArray_1) | 0;
-  result = imul(result, 31) + (this.nullableLongArray_1 == null ? 0 : hashCode(this.nullableLongArray_1)) | 0;
+  result = imul(result, 31) + (this.nullableLongArray_1 == null ? 0 : contentHashCode_4(this.nullableLongArray_1)) | 0;
-  result = imul(result, 31) + hashCode(this.floatArray_1) | 0;
+  result = imul(result, 31) + contentHashCode_5(this.floatArray_1) | 0;
-  result = imul(result, 31) + (this.nullableFloatArray_1 == null ? 0 : hashCode(this.nullableFloatArray_1)) | 0;
+  result = imul(result, 31) + (this.nullableFloatArray_1 == null ? 0 : contentHashCode_5(this.nullableFloatArray_1)) | 0;
-  result = imul(result, 31) + hashCode(this.doubleArray_1) | 0;
+  result = imul(result, 31) + contentHashCode_6(this.doubleArray_1) | 0;
-  result = imul(result, 31) + (this.nullableDoubleArray_1 == null ? 0 : hashCode(this.nullableDoubleArray_1)) | 0;
+  result = imul(result, 31) + (this.nullableDoubleArray_1 == null ? 0 : contentHashCode_6(this.nullableDoubleArray_1)) | 0;
   result = imul(result, 31) + contentDeepHashCode(this.nestedStringArray_1) | 0;
   result = imul(result, 31) + contentDeepHashCode(this.nestedIntArray_1) | 0;
   return result;
 };
```

### CODE REVIEW

**Comment by drewhamilton** [comment]
Data classes compute (shallow) hashCode and toString for array properties! Don't know why, and it's weird that they have different behavior on JS.

Will review tomorrow.

**Comment by JakeWharton** [comment]
This is for content-based properties, not regular ones.

**Comment by drewhamilton** [comment]
Right. The standard data class `hashCode` uses shallow array contents on JVM, and all primitive arrays are shallow, so there was no need to do anything special with `@ArrayContentBased` on primitive array properties in our generated `hashCode` functions.

Since the standard data class `hashCode` apparently *doesn't* use shallow array contents on JS, now there is a need to handle it with the custom logic.

**Review by drewhamilton — APPROVED** [review]

**Comment by JakeWharton** [comment]
Ah, got it.

**Comment by JakeWharton** [comment]
FYI filed https://youtrack.jetbrains.com/issue/KT-60746 about the discrepancy.

**Pull request merged**
