### PR TITLE
Kotlin 2.0.0-RC1

### PR DESCRIPTION
**Pull request by 3flex**
Target branch drew/kotlin-2.0.

androidx-compose-compiler hasn't been built against 2.0.0-RC1 but tests pass locally (except the ones that are expected to fail on Windows).

### CODE REVIEW

**Comment by drewhamilton** [comment]
> \* What went wrong:
Execution failed for task ':kotlinStoreYarnLock'.
\> Lock file was changed. Run the `kotlinUpgradeYarnLock` task to actualize lock file

Want to give that a go?

**Comment by JakeWharton** [comment]
The AndroidX Compose compiler is going away with Kotlin 2.0. The compiler has moved into the Kotlin repo under the JetBrains coordinates. There's also a new Gradle plugin for it that will use dependency substitution to rewrite AGP's use to the new coordinates. I can link more later.

**Comment by 3flex** [comment]
> Want to give that a go?

I'm AFK for the next 10 hours roughly so if you want to move this along feel free to take it forward otherwise I'll do it when I can.

Unfortunately the node setup in the build doesn't work with Windows so I didn't pick this up before sending the PR.

**Comment by JakeWharton** [comment]
Node 22 releases in 13 days which will correct that issue.

**Comment by 3flex** [comment]
I can start here and look at the compose changes: https://youtrack.jetbrains.com/issue/KT-67006

**Comment by JakeWharton** [comment]
Nice. Yeah that has all the relevant info it seems!

**Comment by drewhamilton** [comment]
Thanks for doing this!

**Pull request merged**
