### PR TITLE
Kotlin 2.0.0-RC3

### PR DESCRIPTION
**Pull request by drewhamilton**
Kotlin 2.0 enables the new K2 compiler by default, so non-K2 code paths can be removed.

### CODE REVIEW

**Comment by JakeWharton** [comment]
Can you still opt out though? Or did they completely eliminate the old compiler?

**Comment by drewhamilton** [comment]
Hmm possibly setting an old language version like 1.9 would use the non-K2 compiler. I'll test that out.

**Comment by drewhamilton** [comment]
Confirmed that non-K2 compilation is still possible with language version 1.9. Unfortunately, adding configurations targeting 1.9 in the existing `:poko-tests` module caused errors like the one pasted below, so I had to copy/paste a separate `:poko-tests-without-k2` module. Is there a better approach than having a separate module to test this?

```
A problem occurred configuring project ':poko-tests'.
> Inconsistent settings for Kotlin source sets: 'jvmWithoutK2Main' depends on 'commonMain'
  'jvmWithoutK2Main': language version is KOTLIN_1_9
  'commonMain': language version is KOTLIN_2_0
  The language version of the dependent source set must be greater than or equal to that of its dependency.
```

**Comment by JakeWharton** [comment]
Probably not. Although a separate module might be nice because it can be deleted as a unit more easily once the old compiler is gone for good.

**Comment by drewhamilton** [comment]
2.0.0-Beta3 doesn't like the way we're setting the JVM toolchain in `:poko-tests`:
> e: file:///.../Poko/poko-tests/build.gradle.kts:16:7: Using 'jvmToolchain(Int): Unit' is an error. Configuring JVM toolchain in the Kotlin target level DSL is prohibited. JVM toolchain feature should be configured in the extension scope as it affects all JVM targets (JVM, Android).

**Comment by drewhamilton** [comment]
Found [KT-64629](https://youtrack.jetbrains.com/issue/KT-64629/Gradle-configuration-fails-fun-jvmToolchainjdkVersion-Int-Unit-cant-be-called-in-this-context-by-implicit-receiver): Seems like we can't have multiple JVM targets compiled with different JDKs anymore.

Thinking the best bet will be to build the `:poko-tests` JVM target multiple times with a build matrix, and to reduce the sample build to a single JDK to keep the total builds per PR at a reasonable level.

**Comment by 3flex** [comment]
Since it looks like [Kotlin 2.0.0 will be based on the same commit as 2.0.0-RC3](https://github.com/JetBrains/kotlin/commits/e84e83568cde569ee54980542e37c87507e914bc/), would it be possible to get a rebase & a proper release published to Maven Central, even if it's an alpha/beta version?

It will allow upgrades for dependents when Kotlin 2.0.0 drops without having to add snapshot repos. Thanks!

**Comment by drewhamilton** [comment]
Can do. Since 0.15 is unlikely to need any more releases, I'll merge this with Kotlin 2.0.0-RC3 and release a 0.16 beta version.

**Pull request merged**
